Fix "implicit conversion from floating point to integer" warning
Lora-net/LoRaMac-node pull request #976
Opened 2020-10-22 19:46 UTC by Xeenych

Fix "implicit conversion from floating point to integer" warning
IAR C compiler issues this warning when float si converted to integer implicitly

2020-11-25 13:18 UTC, mluis1 requested changes
A few changes required to comply with current project coding conventions

2020-11-25 13:18 UTC, mluis1 commented on src/apps/LoRaMac/common/CayenneLpp.c
> +    int16_t val = (int16_t) (value * 100);
Please change to
```c
int16_t val = ( int16_t ) ( value * 100 );
```

2020-11-25 13:18 UTC, mluis1 commented on src/apps/LoRaMac/common/CayenneLpp.c
> +    int16_t val = (int16_t) (value * 100);
Please change to

```c
int16_t val = ( int16_t ) ( value * 100 );
```

2020-11-25 13:18 UTC, mluis1 commented on src/apps/LoRaMac/common/CayenneLpp.c
> +    int16_t val = (int16_t) (celsius * 10);
Please change to

```c
int16_t val = ( int16_t ) ( celsius * 10 );
```

2020-11-25 13:18 UTC, mluis1 commented on src/apps/LoRaMac/common/CayenneLpp.c
> +    CayenneLppBuffer[CayenneLppCursor++] = (uint8_t) (rh * 2);
Please change to

```c
CayenneLppBuffer[CayenneLppCursor++] = ( uint8_t ) ( rh * 2 ); 
```

2020-11-25 13:18 UTC, mluis1 commented on src/apps/LoRaMac/common/CayenneLpp.c
> +    int16_t vx = (int16_t) (x * 1000);
Please change to

```c
int16_t vx = ( int16_t ) ( x * 1000 );
```

2020-11-25 13:18 UTC, mluis1 commented on src/apps/LoRaMac/common/CayenneLpp.c
> +    int16_t vy = (int16_t) (y * 1000);
Please change to

```c
int16_t vy = ( int16_t ) ( y * 1000 );
```

2020-11-25 13:18 UTC, mluis1 commented on src/apps/LoRaMac/common/CayenneLpp.c
> +    int16_t vz = (int16_t) (z * 1000);
Please change to

```c
int16_t vz = ( int16_t ) ( z * 1000 );
```

2020-11-25 13:18 UTC, mluis1 commented on src/apps/LoRaMac/common/CayenneLpp.c
> +    int16_t val = (int16_t) (hpa * 10);
Please change to

```c
int16_t val = ( int16_t ) ( hpa * 10 );
```

2020-11-25 13:18 UTC, mluis1 commented on src/apps/LoRaMac/common/CayenneLpp.c
> +    int16_t vx = (int16_t) (x * 100);
Please change to

```c
int16_t vx = ( int16_t ) ( x * 100 );
```

2020-11-25 13:18 UTC, mluis1 commented on src/apps/LoRaMac/common/CayenneLpp.c
> +    int16_t vy = (int16_t) (y * 100);
Please change to

```c
int16_t vy = ( int16_t ) ( y * 100 );
```

2020-11-25 13:18 UTC, mluis1 commented on src/apps/LoRaMac/common/CayenneLpp.c
> +    int16_t vz = (int16_t) (z * 100);
Please change to

```c
int16_t vz = ( int16_t ) ( z * 100 );
```

2020-11-25 13:18 UTC, mluis1 commented on src/apps/LoRaMac/common/CayenneLpp.c
> +    int32_t lat = (int32_t) (latitude * 10000);
Please change to

```c
int32_t lat = ( int32_t ) ( latitude * 10000 );
```

2020-11-25 13:18 UTC, mluis1 commented on src/apps/LoRaMac/common/CayenneLpp.c
> +    int32_t lon = (int32_t) (longitude * 10000);
Please change to

```c
int32_t lon = ( int32_t ) ( longitude * 10000 );
```

2020-11-25 13:18 UTC, mluis1 commented on src/apps/LoRaMac/common/CayenneLpp.c
> +    int32_t alt = (int32_t) (meters * 100);
Please change to

```c
int32_t alt = ( int32_t ) ( meters * 100 );
```

2020-11-26 08:06 UTC, mluis1 commented
I close this pull-request as the requested changes were proposed on a new pull-request #994 

@Xeenych In the future it would be nice to update the original pull-requests instead of creating new ones.

2020-11-26 08:06 UTC, closed without merging

2020-11-26 13:59 UTC, Xeenych commented
I tried to, but I couldn't