AlarmDateWeekDay is 1 - 31
Lora-net/LoRaMac-node pull request #978
Opened 2020-10-25 12:10 UTC by Xeenych

AlarmDateWeekDay is from 1 to 31, so there shoul be a 1 subtracted

2020-11-25 16:27 UTC, mluis1 approved these changes

2020-11-25 16:28 UTC, mluis1 commented
Thanks for the proposition

2020-11-25 16:30 UTC, mluis1 requested changes
Sorry, I have approved the change but it would be nice if you could apply this change to the other platforms.

2020-11-26 06:51 UTC, Xeenych commented
I've made this pull https://github.com/Lora-net/LoRaMac-node/pull/995/ to fix AlarmDateWeekDay in all STm32 boards

2020-11-26 08:02 UTC, mluis1 approved these changes

2020-12-07 12:44 UTC, merged